project:
  type: website
  output-dir: docs/

website:
  title: ""
  navbar:
    left:
      - text: "Home"
        file: index.html
      - text: "Larval Cultures"
        file: cultures.html
      - text: "Larval Ponds"
        file: ponds.html
    right:
      - icon: github
        href: https://github.com/marine-ecologist/larvae
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
